module.exports = {
  AUTHORIZATION_TOKEN: 'No authorization token was found',
  MISSING_PARAMETERS: 'MissingParamsError',
  NOT_ACCEPTABLE: 'NotAcceptable',
  NOT_FOUND: 'NotFound',
  FORBIDDEN: 'Forbidden',
  INVALID_VALUE: 'InvalidValue',
  BAD_REQUEST: 'BadRequest',
  CREDENTIALS_ERROR: 'CredentialsError',
  INVALID_EMAIL: 'ValidEmailError',
  DUPLICATE_EMAIL: 'DuplicateEmailError',
  FILE_UPLOAD_ERROR: 'FileUploadError',
  UNAUTHORIZED_ERROR: 'UnauthorizedError',
  PASSWORD_WONT_MATCH: 'PasswordsUnmatching',
  SHORT_PASSWORD: 'ShortPassword',
  PARAM_MUST_BE_STRING: 'ParametarMustString',
  REPORT_RESON_UNKNOWN: 'NoReportReason',
  OWN_JOB_TRY_FAV: 'OwnJobFavorite',
  NOT_VALID_MONGO_ID: 'NotValidMongoId',
  JWT_MALFORMED: 'jwt malformed',
  LOCATION_UNKNOWN: 'NoLocation',
};
